version: "3.4"

services:
  order:
    image: dapr_api_order:latest
    build:
      context: ./Dapr.API.Order
      target: debug
    ports:
      - "5001:80"

  order-dapr:
    image: daprio/daprd:latest
    command:
      [
        "./daprd",
        "-app-id",
        "order",
        "-app-port",
        "80",
        "--components-path",
        "/components",
        "--app-protocol",
        "http",
      ]
    depends_on:
      - order
      - redis
    network_mode: "service:order"
    volumes:
      - ./Dapr/Components:/components

  product:
    image: dapr_api_product:latest
    build:
      context: ./Dapr.API.Product
      target: debug
    ports:
      - "5002:80"

  product-dapr:
    image: daprio/daprd:latest
    command:
      [
        "./daprd",
        "-app-id",
        "product",
        "-app-port",
        "80",
        "--components-path",
        "/components",
      ]
    depends_on:
      - product
      - redis
    network_mode: "service:product"
    volumes:
      - ./Dapr/Components:/components

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123456
