version: "3.4"

services:
  order:
    image: dapr_api_order:latest
    build:
      context: ./Dapr.API.Order/Dockerfile
      target: debug
    ports:
      - "5001:80"

  order-dapr:
    image: daprio/daprd:latest
    command: ["./daprd", "-app-id", "order", "-app-port", "80"]
    depends_on:
      - order
    network_mode: "service:order"

  product:
    image: dapr_api_product:latest
    build:
      context: ./Dapr.API.Product/Dockerfile
      target: debug
    ports:
      - "5002:80"

  product-dapr:
    image: daprio/daprd:latest
    command: ["./daprd", "-app-id", "product", "-app-port", "80"]
    depends_on:
      - product
    network_mode: "service:product"
